### ISSUE TITLE
about restriction of 'Reduce to names and avoiding qualified expressions [mistake]

### ISSUE THREAD

**Issue by evanescente-ondine** [Ada-Rapporteur-Group/UCI-Prototype#116]
Hi,
Should expressions like these be allowed ?
> function Count_of_A (G: String) RETURN Natural IS ((for E of G => (if E = 'a' then 1 else 0)'Reduce("+", 0));

I get
> main.adb:4:49: error: prefix of attribute must be a name
main.adb:4:49: error: qualify expression to turn it into a name

because `(for E of G => (if E = 'a' then 1 else 0)` is not  a "name". Not sure if it falls under the label of value or expression, but in any case its type and range is self-evident, but because it has no explicit type definition the 'Reduce attribute refuses it, asking for a qualified expression. The problem is we can not declare such a type inside an expression, so it makes using 'Reduce inside an expression function for instance, not possible in many cases.
Could 'Reduce work with all values of an array or container type (anything that fits in a pair of square brackets) and can be iterated upon ?

**Comment by sttaft** [comment]
Can you clarify exactly what is your question?  
[I made a couple of edits to make it syntactically legal]

**Comment by evanescente-ondine** [comment]
I hope the new wording makes more sense.

**Comment by sttaft** [comment]
You are required to use *either* a name, *or* an iterator in square brackets (not parentheses), in the prefix of the 'Reduce attribute reference (see RM 4.5.10).  Did you try:
```
function Count_of_A (G: String) RETURN Natural
  IS ([for E of G => (if E = 'a' then 1 else 0)]'Reduce("+", 0))
```
The GNAT error message could definitely be improved ...

**Comment by sttaft** [comment]
The reference manual (RM 4.5.10 (35/5-36/5)) has an example of almost exactly what you are trying to do:

> {[AI12-0262-1](http://www.ada-auth.org/cgi-bin/cvsweb.cgi/AI12s/AI12-0262-1.TXT)} {[AI12-0429-1](http://www.ada-auth.org/cgi-bin/cvsweb.cgi/AI12s/AI12-0429-1.TXT)} Example of an expression function that returns its result as a reduction expression:
> ```
> function Factorial(N : Natural) return Natural is
>    ([for J in 1..N => J]'Reduce("*", 1));
> ```

**Comment by evanescente-ondine** [comment]
??!? Sorry, I don't understand what went wrong. I tried several times and I missed what works ? But yes the compiler confused the hell out of me there... Thanks for the clarifying, I'll keep that thread in mind for when the issue pops again.

**Comment by sttaft** [comment]
Glad you got it to work.  One confusing error message can definitely lead to a wild goose chase.
