### ISSUE TITLE
4.3.5 (61) needs updating

### ISSUE THREAD

**Issue by ronan-d** [Ada-Rapporteur-Group/UCI-Prototype#88]
With the recent change to 4.3.5 (6), the example in 4.3.5 (61) is no longer valid and `Empty_Map` needs to be made a function instead of a constant.

**Comment by CKWG** [comment]
This is just an example, but good practice should also apply in examples, and a negative Capacity does not make much sense.
(63/6)   function Empty_Vector (Capacity : Natural := 0) return Vector_Type;

**Comment by ARG-Editor** [comment]
Both of these issues were added to [AI22-0098-1](https://docs.google.com/document/d/1nghc-sfvFIQhqVm4ou_jzpwxhrPrnaozHoxTn3VateQ), which is likely to be considered at the next ARG meeting.

**Comment by ARG-Editor** [comment]
[AI22-0098-1](https://docs.google.com/document/d/1nghc-sfvFIQhqVm4ou_jzpwxhrPrnaozHoxTn3VateQ) was approved at ARG meeting #63D; this issue is completed.
